name: Build

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Java 8
              uses: actions/setup-java@v1
              with:
                  java-version: 8

            - name: Cache gradle dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('gradle.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Build with Gradle
              run: ./gradlew build --no-daemon || ./gradlew build --no-daemon

            - name: Upload Jar
              uses: actions/upload-artifact@v1
              with:
                  name: CC-Tweaked-Fabric
                  path: build/libs